smoke test failure

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -375,28 +375,44 @@ jobs:
       - revert-migrations
       - notify_on_failure
 
-#   smoke-test:
-#     docker:
-#       # Lightweight Docker image 
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Get backend url
-#           command: |
-#             # your code here
-#       - run:
-#           name: Backend smoke test.
-#           command: |
-#             # your code here
-#       - run:
-#           name: Frontend smoke test.
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+  smoke-test:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      # Checkout code from git
+      - checkout
+      - install_aws_cli
+      - install_nodejs
+      - run:
+          name: Backend smoke test.
+          command: |
+            # your code here
+            BACKEND_IP=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --output text)
+            export API_URL=http://${BACKEND_IP}:3030
+            if curl -s $API_URL/api/status | grep "ok"
+            then 
+              exit 1
+            else
+              exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+            FRONTEND_URL=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            if curl -s $FRONTEND_URL | grep "Welcome"
+            then
+              exit 0
+            else
+              exit 1
+            fi    
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment
+      - revert-migrations
+      - notify_on_failure
 
 #   cloudfront-update:
 #     docker:
@@ -458,7 +474,9 @@ workflows:
       - deploy-frontend:
           requires: [run-migrations] 
       - deploy-backend:
-          requires: [run-migrations]       
+          requires: [run-migrations]   
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]        
       - notify-on-success:
           requires:
             - build-frontend
@@ -472,10 +490,10 @@ workflows:
             - run-migrations  
             - deploy-frontend  
             - deploy-backend
+            - smoke-test
       
       
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
+      
       # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
